### ISSUE TITLE
Skroutz API

### ISSUE THREAD

**Issue by Kotsifakisgeniuspet** [sp1thas/pyskroutz#15]
Καλησπέρα σας,

προσπαθώ εδώ και μερικές ημέρες να χρησιμοποιήσω το pyskroutz δύχως κανένα θετικό αποτέλεσμα, υπάρχει κάποιο document που θα μπορούσαμε να διαβάσουμε....π.χ που βρίσκουμε το client-id, client secret, πως κάνουμε parse token για auth?.

Σας ευχαριστώ πολύ.

**Comment by sp1thas** [comment]
Hey, thanks for reaching out. I'm sorry to hear that you are facing authentication issues. In order to use this module, you have to already own a pair of client-id and client-secret. It's seems that Skroutz does not provide API access to new users. So, you have to contact Skroutz directly in order to verify if it's possible to get access or not. [Here](https://developer.skroutz.gr/support/#contact) you will find the contact details. Given that this issue is related to Skroutz API and not the current package, I'm closing it.
